// Auto-generated by refresh.py — do not edit manually
// Last updated: 2026-05-28
window.DASHBOARD_DATA = {
  generated: "2026-05-28",
  fiscalYear: 2026,

  // Meetings per month — pre-sale accounts only (accounts with active pipeline)
  meetingsPerMonth: [
    { month: "Jan 2026", meetings: 11 },
    { month: "Feb 2026", meetings: 26 },
    { month: "Mar 2026", meetings: 37 },
    { month: "Apr 2026", meetings: 54 },
    { month: "May 2026", meetings: 38 },
    { month: "Jun 2026", meetings: 6 },
    { month: "Jul 2026", meetings: 1 }
  ],

  // Pipeline value by stage (open opportunities)
  pipelineByStage: [
    { stage: "Qualify",    value: 526200,  count: 25 },
    { stage: "Explore",    value: 749400,  count: 23 },
    { stage: "Active",     value: 376100,  count: 26 },
    { stage: "Propose",    value: 658200,  count: 24 },
    { stage: "Negotiate",  value: 178200,  count: 4  },
    { stage: "Demo Config",value: 6000,    count: 1  }
  ],

  // New pipeline created per month (opportunity CreatedDate)
  pipelineGrowth: [
    { month: "Feb 2026", count: 184, value: 4785805 },
    { month: "Mar 2026", count: 8,   value: 218040  },
    { month: "Apr 2026", count: 6,   value: 164400  },
    { month: "May 2026", count: 21,  value: 501600  }
  ],

  // Summary KPIs
  summary: {
    totalOpenPipelineValue: 2494100,
    totalOpenOpportunities: 103,
    presaleAccounts: 94,
    ytdMeetings: 173,
    avgMonthlyMeetings: 24.7
  }
};
