// Auto-generated by refresh.py — do not edit manually
// Last updated: 2026-05-29
window.DASHBOARD_DATA = {
  "generated": "2026-05-29",
  "fiscalYear": 2026,
  "meetingsPerMonth": [
    { "month": "Jan 2026", "meetings": 6 },
    { "month": "Feb 2026", "meetings": 9 },
    { "month": "Mar 2026", "meetings": 10 },
    { "month": "Apr 2026", "meetings": 14 },
    { "month": "May 2026", "meetings": 26 },
    { "month": "Jun 2026", "meetings": 3 },
    { "month": "Jul 2026", "meetings": 1 },
    { "month": "Sep 2026", "meetings": 1 }
  ],
  "pipelineByStage": [
    { "stage": "Qualify",   "value": 462000, "count": 23 },
    { "stage": "Explore",   "value": 665400, "count": 21 },
    { "stage": "Propose",   "value": 544200, "count": 21 },
    { "stage": "Negotiate", "value": 84000,  "count": 2  }
  ],
  "pipelineGrowth": [
    { "month": "Feb 2026", "count": 142, "value": 3956400 },
    { "month": "Mar 2026", "count": 4,   "value": 106800  },
    { "month": "Apr 2026", "count": 5,   "value": 134400  },
    { "month": "May 2026", "count": 19,  "value": 441600  }
  ],
  "summary": {
    "totalOpenPipelineValue": 1755600,
    "totalOpenOpportunities": 67,
    "presaleAccounts": 766,
    "ytdMeetings": 70,
    "avgMonthlyMeetings": 8.8
  }
};
