#!/usr/bin/env python3
"""
refresh.py — Re-pulls Salesforce data via Composio and rewrites data.js.
Run this script whenever you want to update the dashboard with fresh data.

Requirements:
    pip install composio-openai

Setup:
    1. Set COMPOSIO_API_KEY in your environment or a .env file.
    2. Run: composio add salesforce   (only needed once to connect your account)
    3. Then: python refresh.py

The script overwrites data.js in the same directory. Commit & push to GitHub
Pages to publish the update.
"""

import json
import os
import sys
from datetime import date, datetime
from collections import defaultdict

try:
    from composio_openai import ComposioToolSet
except ImportError:
    print("ERROR: composio-openai not installed. Run: pip install composio-openai")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
FISCAL_YEAR = date.today().year
PIPELINE_STAGES = {'Qualify', 'Explore', 'Propose', 'Negotiate', 'Nurture'}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Composio client
# ---------------------------------------------------------------------------
toolset = ComposioToolSet()

def soql(query: str) -> list[dict]:
    """Run a SOQL query via Composio and return records list."""
    result = toolset.execute_action(
        action="SALESFORCE_RUN_SOQL_QUERY",
        params={"query": query},
    )
    if result.get("error"):
        raise RuntimeError(f"SOQL error: {result['error']}\nQuery: {query}")
    return result.get("data", {}).get("records", [])

# ---------------------------------------------------------------------------
# Pull data
# ---------------------------------------------------------------------------
print("Pulling Salesforce data...")

# 1. Open pipeline opps with owner
raw_opps = soql(
    "SELECT Id, StageName, Amount, CreatedDate, AccountId, Owner.Name "
    "FROM Opportunity "
    "WHERE StageName IN ('Qualify','Explore','Propose','Negotiate','Nurture') "
    "AND AccountId != null LIMIT 2000"
)
print(f"  Open pipeline opps: {len(raw_opps)}")

# 2. All opps this FY (for growth chart)
raw_all_opps = soql(
    f"SELECT Id, StageName, Amount, CreatedDate, AccountId, Owner.Name "
    f"FROM Opportunity "
    f"WHERE CreatedDate >= {FISCAL_YEAR}-01-01T00:00:00Z "
    f"AND StageName IN ('Qualify','Explore','Propose','Negotiate','Nurture') "
    f"AND AccountId != null LIMIT 2000"
)
print(f"  FY{FISCAL_YEAR} pipeline opps: {len(raw_all_opps)}")

# 3. Events this FY with owner
raw_events = soql(
    f"SELECT Id, ActivityDate, AccountId, Owner.Name "
    f"FROM Event "
    f"WHERE ActivityDate >= {FISCAL_YEAR}-01-01 AND ActivityDate <= {FISCAL_YEAR}-12-31 "
    f"AND AccountId != null LIMIT 2000"
)
print(f"  Events: {len(raw_events)}")

# ---------------------------------------------------------------------------
# Shape records
# ---------------------------------------------------------------------------
def owner_name(rec):
    o = rec.get("Owner")
    if isinstance(o, dict):
        return o.get("Name", "Unknown")
    return "Unknown"

opps = [
    {
        "id": r["Id"],
        "stage": r.get("StageName", ""),
        "amount": r.get("Amount") or 0,
        "createdDate": (r.get("CreatedDate") or "")[:10],
        "accountId": r.get("AccountId", ""),
        "ownerName": owner_name(r),
    }
    for r in raw_opps
]

all_opps = [
    {
        "id": r["Id"],
        "stage": r.get("StageName", ""),
        "amount": r.get("Amount") or 0,
        "createdDate": (r.get("CreatedDate") or "")[:10],
        "accountId": r.get("AccountId", ""),
        "ownerName": owner_name(r),
    }
    for r in raw_all_opps
]

# Remove Feb from growth (new seller ramp distorts the trend)
all_opps = [o for o in all_opps if not o["createdDate"].startswith(f"{FISCAL_YEAR}-02")]

events = [
    {
        "id": r["Id"],
        "activityDate": r.get("ActivityDate", ""),
        "accountId": r.get("AccountId", ""),
        "ownerName": owner_name(r),
    }
    for r in raw_events
]

# Filter events to future months out
current_month = date.today().strftime("%Y-%m")
events = [e for e in events if (e["activityDate"] or "")[:7] <= current_month]

owners = sorted({o["ownerName"] for o in opps} | {e["ownerName"] for e in events})

# ---------------------------------------------------------------------------
# Build data.js
# ---------------------------------------------------------------------------
output = {
    "generated": date.today().isoformat(),
    "fiscalYear": FISCAL_YEAR,
    "owners": owners,
    "opps": opps,
    "allOpps": all_opps,
    "events": events,
}

js_content = (
    "// Auto-generated by refresh.py — do not edit manually\n"
    f"// Last updated: {date.today().isoformat()}\n"
    "window.DASHBOARD_DATA = " + json.dumps(output) + ";\n"
)

out_path = os.path.join(SCRIPT_DIR, "data.js")
with open(out_path, "w") as f:
    f.write(js_content)

print(f"\nDone! data.js updated.")
print(f"  Open pipeline opps: {len(opps)}")
print(f"  Owners: {', '.join(owners)}")
print(f"\nTo publish: git add data.js && git commit -m 'refresh: {date.today()}' && git push")
